
include :
  - .htaccess
  - .htaccess_static
plugins :
  - jekyll-assets

assets : 
  sources       : [_assets]
  destination   : /assets
  digest        : true
  source_maps   : false
  compression   : false
  gzip          : false
  caching       :
    enabled : false