plugins :
  - jekyll-assets

assets : 
  sources       : [_assets, _customfolder]
  destination   : /assets
  digest        : true
  source_maps   : false
  compression   : false
  gzip          : false
  defaults      :
    js      : { integrity: true }
    css     : { integrity: true }
    img     : { integrity: true }
  caching       :
    enabled : false