plugins :
  - jekyll-assets
  - jekyll-paginate
  - autoprefixer-rails

assets : 
  sources       : [_assets, customfolder]
  destination   : /assets
  digest        : true
  source_maps   : false
  compression   : false
  gzip          : false
  defaults      :
    js      : { integrity: true }
    css     : { integrity: true }
    img     : { integrity: true }
  caching       :
    enabled : false
  precompile    : []
  plugins       :
    css     : { autoprefixer: {}}