
email : "&#116;&#99;&#97;&#116;&#110;&#111;&#99;&#124;&#109;&#111;&#99;&#46;&#97;&#103;&#110;&#97;&#103;&#115;&#101;&#114;&#97;&#112;&#115;&#97;&#103;"

include :
  - .htaccess
  - .htaccess_static
plugins :
  - jekyll-assets

assets : 
  sources       : [_assets]
  destination   : /assets
  digest        : true
  source_maps   : false
  compression   : false
  gzip          : false
  caching       :
    enabled : false