
email : "&#110;&#111;&#115;&#112;&#097;&#109;&#104;&#101;&#114;&#101;&#064;&#101;&#120;&#097;&#109;&#112;&#108;&#101;&#046;&#099;&#111;&#109;"

include :
  - .htaccess
  - .htaccess_static
plugins :
  - jekyll-assets

assets : 
  sources       : [_assets]
  destination   : /assets
  digest        : true
  source_maps   : false
  compression   : false
  gzip          : false
  caching       :
    enabled : false